app:
  wecom:
    corpId: ${wecom.corpId}
    appAgentId: ${wecom.appAgentId}
    appSecret: ${wecom.appSecret}
    api:
      requestPrefix: https://qyapi.weixin.qq.com/cgi-bin/
    tokenCache:
      # guava or redis
      type: redis
      expiredTimeInSecond: 7200
      # unit: millisecond. 10 minutes = 600000 millisecond
      refreshTokenTaskRate: 600000
spring:
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 0
  config:
    # additional configuration file path
    # passed by OS environment variables or Command Line Properties
    import: D:\config\wecom\application-my.yml
