spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # Single datasource.
      # If you want to use this, you need to check the multiple datasource Java configuration @Configuration is removed.
      url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/master/*.xml
  type-aliases-package: com.taogen.example.entity
