#spring:
#  config:
#    import: classpath:parent.application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.taogen.demo.domain
  global-config:
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
