spring:
  config:
    import: D:\config\gitee-application.yml
  security:
    user:
      name: admin
      password: admin123
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          timeout: 10
          # Suggest using Gitee for Chinese users. Using GitHub URL often throws connect timeout exception.
          uri: https://gitee.com/tagnja/spring-cloud-config.git
          username: taogenjia@gmail.com
          password: ${giteePersonalAccessToken}
          default-label: master
server:
  port: 8888

