spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 0
  profiles:
    # jedis, lettuce. For @Profile on Redis Config
    active: jedis
