spring:
  profiles:
    # git-https, git-local, git-ssh, local-files
    active: git-https
# local system file config need spring.profiles.active=native, so use spring.config.import
#  config:
#    import: classpath:application-local-files.yml
