spring:
  datasource:
    db1:
      url: jdbc:mysql://localhost:3306/my_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123
      driverClassName: com.mysql.cj.jdbc.Driver
    db2:
      url: jdbc:mysql://localhost:4306/my_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root123
      driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
